[tool.poetry]
package-mode = false

[project]
name = "database-repository-pattern-example"
version = "1.1.0"
description = "Repository pattern example with SQL Server and a basic Flask page."
authors = [{ name = "Josh Weese" }]
requires-python = ">=3.10,<4.0"
dynamic = ["dependencies"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
flask = "*"
mssql-python = "*"

[tool.poetry.group.dev.dependencies]
coverage = "*"
flake8 = "*"
flake8-docstrings = "*"
flake8-html = "*"
lxml = "*"
mypy = "*"
pdoc3 = "*"
pep8-naming = "*"
pyhamcrest = "*"
pytest = "*"
pytest-html = "*"
pytest-cov= "*"
python-dotenv = "*"


