// Package repositories provides data access layer for the company application
// Authors:
// 	- Jared Paubel
//  - OpenCode agent - local qwen/qwen3.5-9b
// Percentage written by Agent: 95%

package repositories

import (
	"context"
	"database/sql"
	"sync"

	"cc520-company-dbms-project/src/company/app/backend/models"
	"cc520-company-dbms-project/src/company/db/executor"
)

// EmployeeRepository handles data access for Employee entities.
// Currently returning fake data as requested.
type EmployeeRepository struct {
	executor *executor.Executor
	mu       sync.RWMutex
	fakeData map[int64]models.Employee
	nextID   int64
}

// NewEmployeeRepository creates a new EmployeeRepository instance with fake data
func NewEmployeeRepository(executor *executor.Executor) *EmployeeRepository {
	repo := &EmployeeRepository{
		executor: executor,
		fakeData: make(map[int64]models.Employee),
		nextID:   4,
	}

	// Initialize with some fake data (Generated by Gemini)
	repo.fakeData[1] = models.Employee{
		EmployeeID:       1,
		CompanyID:        1,
		DepartmentID:     1,
		Department:       "Engineering",
		FirstName:        "Alice",
		LastName:         "Smith",
		Email:            "alice.smith@example.com",
		Phone:            "555-0101",
		Street:           "123 Tech Lane",
		City:             "San Francisco",
		State:            "CA",
		ZipCode:          "94105",
		RoleTitle:        "Engineering Manager",
		ManagerName:      "N/A",
		HireDate:         "2020-01-15",
		TerminationDate:  "",
		StatusType:       "Salary",
		BaseSalary:       180000.00,
		Bonus:            20000.00,
		Deductions:       500.00,
		PaidTimeOffHours: 120,
		SickHours:        40,
		EffectiveFrom:    "2024-01-01",
		EffectiveTo:      "2025-01-01",
	}
	repo.fakeData[2] = models.Employee{
		EmployeeID:       2,
		CompanyID:        1,
		DepartmentID:     2,
		Department:       "Human Resources",
		FirstName:        "Bob",
		LastName:         "Jones",
		Email:            "bob.jones@example.com",
		Phone:            "555-0102",
		Street:           "456 People Blvd",
		City:             "San Francisco",
		State:            "CA",
		ZipCode:          "94105",
		RoleTitle:        "HR Manager",
		ManagerName:      "Alice Smith",
		HireDate:         "2021-03-10",
		TerminationDate:  "",
		StatusType:       "Salary",
		BaseSalary:       110000.00,
		Bonus:            5000.00,
		Deductions:       200.00,
		PaidTimeOffHours: 80,
		SickHours:        40,
		EffectiveFrom:    "2024-01-01",
		EffectiveTo:      "2025-01-01",
	}
	repo.fakeData[3] = models.Employee{
		EmployeeID:      3,
		CompanyID:       1,
		DepartmentID:    1,
		Department:      "Engineering",
		FirstName:       "Charlie",
		LastName:        "Brown",
		Email:           "charlie.brown@example.com",
		Phone:           "555-0103",
		Street:          "789 Code Way",
		City:            "San Francisco",
		State:           "CA",
		ZipCode:         "94107",
		RoleTitle:       "Junior Developer",
		ManagerName:     "Alice Smith",
		HireDate:        "2023-06-01",
		TerminationDate: "",
		StatusType:      "Hourly",
		HourlyPay:       45.50,
		MaxHoursPerWeek: 40,
	}

	return repo
}

// GetAllEmployees retrieves all employees
func (r *EmployeeRepository) GetAllEmployees(ctx context.Context) ([]models.Employee, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	employees := make([]models.Employee, 0, len(r.fakeData))
	for _, emp := range r.fakeData {
		employees = append(employees, emp)
	}
	return employees, nil
}

// GetEmployeeByID retrieves an employee by ID
func (r *EmployeeRepository) GetEmployeeByID(ctx context.Context, id int64) (*models.Employee, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	emp, exists := r.fakeData[id]
	if !exists {
		return nil, sql.ErrNoRows
	}
	return &emp, nil
}

// CreateEmployee creates a new employee (fake implementation)
func (r *EmployeeRepository) CreateEmployee(ctx context.Context, emp models.Employee) (*models.Employee, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	emp.EmployeeID = r.nextID
	r.nextID++
	r.fakeData[emp.EmployeeID] = emp

	return &emp, nil
}

// UpdateEmployee updates an existing employee (fake implementation)
func (r *EmployeeRepository) UpdateEmployee(ctx context.Context, emp models.Employee) (*models.Employee, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	if _, exists := r.fakeData[emp.EmployeeID]; !exists {
		return nil, sql.ErrNoRows
	}
	r.fakeData[emp.EmployeeID] = emp
	return &emp, nil
}

// DeleteEmployee deletes an employee by ID (fake implementation)
func (r *EmployeeRepository) DeleteEmployee(ctx context.Context, id int64) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if _, exists := r.fakeData[id]; !exists {
		return sql.ErrNoRows
	}
	delete(r.fakeData, id)
	return nil
}
