DECLARE @AddressStaging TABLE
(
    AddressID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    AddressLineOne NVARCHAR(255) NOT NULL,
    AddressLineTwo NVARCHAR(255),
    CityName NVARCHAR(100) NOT NULL,
    State NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(20) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @AddressStaging(AddressLineOne, AddressLineTwo, CityName, State, ZipCode)
VALUES
-- EXECUTIVES
-- CEO Address (1)
(N'100 Executive Drive', NULL, N'Seattle', N'WA', N'98101'),
-- HR
(N'225 Maple Street', N'Apt 1', N'Seattle', N'WA', N'98102'),
-- Finance
(N'336 Oak Avenue', NULL, N'Seattle', N'WA', N'98103'),
-- Sales
(N'447 Pine Road', N'Unit 2', N'Seattle', N'WA', N'98104'),
-- Marketing
(N'558 Elm Street', NULL, N'Seattle', N'WA', N'98105'),
-- Engineering
(N'669 Cedar Lane', N'Floor 3', N'Seattle', N'WA', N'98106'),

-- DIRECTORS
-- HR
(N'770 Birch Boulevard', NULL, N'Seattle', N'WA', N'98107'),
-- Finance
(N'881 Willow Way', N'Apt 5', N'Seattle', N'WA', N'98108'),
-- Sales
(N'992 Spruce Court', NULL, N'Seattle', N'WA', N'98109'),
-- Marketing
(N'103 Ash Drive', N'Unit 1', N'Seattle', N'WA', N'98110'),
-- Engineering
(N'114 Chestnut Street', NULL, N'Seattle', N'WA', N'98111'),

-- MANAGERS
-- HR
(N'225 Walnut Avenue', N'Apt 2', N'Seattle', N'WA', N'98112'),
-- Finance
(N'336 Hickory Road', NULL, N'Seattle', N'WA', N'98113'),
-- Sales
(N'447 Magnolia Lane', N'Unit 3', N'Seattle', N'WA', N'98114'),
-- Marketing
(N'558 Sycamore Court', NULL, N'Seattle', N'WA', N'98115'),
-- Engineering
(N'669 Redwood Place', N'Apt 4', N'Seattle', N'WA', N'98116'),

-- HR Department Addresses (10)
(N'770 Chestnut Way', NULL, N'Seattle', N'WA', N'98117'),
(N'881 Juniper Drive', N'Unit 5', N'Seattle', N'WA', N'98118'),
(N'992 Fir Street', NULL, N'Seattle', N'WA', N'98119'),
(N'103 Beech Avenue', N'Apt 6', N'Seattle', N'WA', N'98120'),
(N'214 Dogwood Boulevard', NULL, N'Seattle', N'WA', N'98121'),
(N'325 Laurel Circle', N'Unit 1', N'Seattle', N'WA', N'98122'),
(N'436 Cottonwood Terrace', NULL, N'Seattle', N'WA', N'98123'),
(N'547 Hemlock Heights', N'Apt 2', N'Seattle', N'WA', N'98124'),
(N'658 Sequoia Estates', NULL, N'Seattle', N'WA', N'98125'),
(N'769 Acacia Manor', N'Unit 3', N'Seattle', N'WA', N'98126'),
-- Finance Department Addresses (10)
(N'870 Mesquite Park', NULL, N'Seattle', N'WA', N'98127'),
(N'981 Baobab Glen', N'Apt 4', N'Seattle', N'WA', N'98128'),
(N'192 Ironwood Ridge', NULL, N'Seattle', N'WA', N'98129'),
(N'203 Teak Hills', N'Unit 5', N'Seattle', N'WA', N'98130'),
(N'314 Rosewood Valley', NULL, N'Seattle', N'WA', N'98131'),
(N'425 Sandalwood Creek', N'Apt 1', N'Seattle', N'WA', N'98132'),
(N'536 Palmetto Springs', NULL, N'Seattle', N'WA', N'98133'),
(N'647 Buttonwood Falls', N'Unit 2', N'Seattle', N'WA', N'98134'),
(N'758 Ironbark Woods', NULL, N'Seattle', N'WA', N'98135'),
(N'869 Blackwood Grove', N'Apt 3', N'Seattle', N'WA', N'98136'),
-- Sales Department Addresses (10)
(N'970 Silverwood Forest', NULL, N'Seattle', N'WA', N'98137'),
(N'181 Goldwood Meadow', N'Unit 4', N'Seattle', N'WA', N'98138'),
(N'292 Bronzewood Summit', NULL, N'Seattle', N'WA', N'98139'),
(N'303 Copperwood Peak', N'Apt 5', N'Seattle', N'WA', N'98140'),
(N'414 Maplewood Canyon', NULL, N'Seattle', N'WA', N'98141'),
(N'525 Oakwood Valley', N'Unit 1', N'Seattle', N'WA', N'98142'),
(N'636 Pinewood Ridge', NULL, N'Seattle', N'WA', N'98143'),
(N'747 Cedarwood Glen', N'Apt 2', N'Seattle', N'WA', N'98144'),
(N'858 Birchwood Park', NULL, N'Seattle', N'WA', N'98145'),
(N'969 Willowbrook Estate', N'Unit 3', N'Seattle', N'WA', N'98146'),
-- Marketing Department Addresses (10)
(N'170 Sprucewood Manor', NULL, N'Seattle', N'WA', N'98147'),
(N'281 Ashwood Heights', N'Apt 4', N'Seattle', N'WA', N'98148'),
(N'392 Poplarwood Summit', NULL, N'Seattle', N'WA', N'98149'),
(N'403 Walnutwood Peak', N'Unit 5', N'Seattle', N'WA', N'98150'),
(N'514 Redwood Heights', NULL, N'Seattle', N'WA', N'98151'),
(N'625 Cypress Valley', N'Apt 1', N'Seattle', N'WA', N'98152'),
(N'736 Sequoia Ridge', NULL, N'Seattle', N'WA', N'98153'),
(N'847 Juniper Glen', N'Unit 2', N'Seattle', N'WA', N'98154'),
(N'958 Fir Park', NULL, N'Seattle', N'WA', N'98155'),
(N'169 Pine Estate', N'Apt 3', N'Seattle', N'WA', N'98156'),
-- Engineering Department Addresses (10)
(N'270 Cedar Manor', NULL, N'Seattle', N'WA', N'98157'),
(N'381 Birch Heights', N'Unit 4', N'Seattle', N'WA', N'98158'),
(N'492 Willow Summit', NULL, N'Seattle', N'WA', N'98159'),
(N'503 Spruce Peak', N'Apt 5', N'Seattle', N'WA', N'98160'),
(N'614 Ash Valley', NULL, N'Seattle', N'WA', N'98161'),
(N'725 Elm Grove', NULL, N'Seattle', N'WA', N'98162'),
(N'836 Oak Ridge', N'Unit 2', N'Seattle', N'WA', N'98163'),
(N'947 Pine Creek', NULL, N'Seattle', N'WA', N'98164'),
(N'1058 Maple Drive', N'Apt 3', N'Seattle', N'WA', N'98165'),
(N'1169 Cedar Lane', NULL, N'Seattle', N'WA', N'98166');

MERGE Org.Address T
USING (SELECT * FROM @AddressStaging) S ON T.AddressID = S.AddressID
WHEN MATCHED AND (
    T.AddressLineOne <> S.AddressLineOne
    OR T.AddressLineTwo <> S.AddressLineTwo
    OR T.CityName <> S.CityName
    OR T.State <> S.State
    OR T.ZipCode <> S.ZipCode
) THEN
    UPDATE SET
        AddressLineOne = S.AddressLineOne,
        AddressLineTwo = S.AddressLineTwo,
        CityName = S.CityName,
        State = S.State,
        ZipCode = S.ZipCode
WHEN NOT MATCHED THEN
    INSERT(AddressLineOne, AddressLineTwo, CityName, State, ZipCode)
    VALUES(S.AddressLineOne, S.AddressLineTwo, S.CityName, S.State, S.ZipCode);
