DECLARE @EmployeeStaging TABLE
(
    ManagerID INT,
    PersonID INT NOT NULL,
    EmployeeTypeID INT NOT NULL,
    HireDate DATETIME2 NOT NULL,
    TerminationDate DATETIME2
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @EmployeeStaging(ManagerID, PersonID, EmployeeTypeID, HireDate, TerminationDate)
VALUES
(NULL, 1, 1, '2020-01-15T00:00:00', NULL),  -- CEO (no manager)
(1, 2, 1, '2018-03-20T00:00:00', NULL),  -- CTO (reports to CEO)
(1, 3, 1, '2019-06-10T00:00:00', NULL),  -- CFO (reports to CEO)
(1, 4, 1, '2017-11-05T00:00:00', NULL),  -- HR Manager (reports to CEO)
(1, 5, 1, '2019-02-28T00:00:00', NULL),  -- Sales Manager (reports to CEO)
(1, 6, 1, '2020-08-15T00:00:00', NULL),  -- Marketing Manager (reports to CEO)
(2, 7, 1, '2021-01-10T00:00:00', NULL),  -- Senior Engineer (reports to CTO)
(2, 8, 1, '2021-03-15T00:00:00', NULL),  -- Developer (reports to CTO)
(2, 9, 1, '2021-05-20T00:00:00', NULL),  -- Developer (reports to CTO)
(2, 10, 1, '2021-07-01T00:00:00', NULL); -- Developer (reports to CTO)

MERGE Org.Employee T
USING (SELECT * FROM @EmployeeStaging) S ON T.PersonID = S.PersonID
WHEN MATCHED AND (
    T.ManagerID <> S.ManagerID OR
    T.EmployeeTypeID <> S.EmployeeTypeID OR
    T.HireDate <> S.HireDate OR
    T.TerminationDate <> S.TerminationDate
) THEN
    UPDATE SET 
        ManagerID = S.ManagerID,
        EmployeeTypeID = S.EmployeeTypeID,
        HireDate = S.HireDate,
        TerminationDate = S.TerminationDate
WHEN NOT MATCHED THEN
    INSERT(ManagerID, PersonID, EmployeeTypeID, HireDate, TerminationDate)
    VALUES(S.ManagerID, S.PersonID, S.EmployeeTypeID, S.HireDate, S.TerminationDate);
