DECLARE @AddressStaging TABLE
(
    AddressID INT NOT NULL,
    AddressLineOne NVARCHAR(255) NOT NULL,
    AddressLineTwo NVARCHAR(255),
    CityName NVARCHAR(100) NOT NULL,
    [State] NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(20) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b & Gemini
INSERT @AddressStaging(AddressID, AddressLineOne, AddressLineTwo, CityName, [State], ZipCode) VALUES
(1, N'7277 Pine Blvd', N'Apt 44', N'Denver', N'CA', N'98876'),
(2, N'1656 Maple Rd', N'Apt 65', N'Portland', N'WA', N'98373'),
(3, N'4194 Elm Rd', NULL, N'Austin', N'TX', N'98544'),
(4, N'7568 Cedar Rd', NULL, N'Seattle', N'CA', N'98538'),
(5, N'9121 Pine Blvd', N'Apt 20', N'Denver', N'CA', N'98141'),
(6, N'1213 Oak Rd', NULL, N'Denver', N'CO', N'98932'),
(7, N'8229 Cedar Rd', NULL, N'San Francisco', N'OR', N'98201'),
(8, N'7696 Oak St', NULL, N'Denver', N'TX', N'98955'),
(9, N'387 Maple Rd', N'Apt 51', N'Denver', N'TX', N'98169'),
(10, N'3627 Cedar Rd', NULL, N'Portland', N'CO', N'98155'),
(11, N'9925 Oak Ave', NULL, N'Austin', N'TX', N'98690'),
(12, N'3272 Maple Blvd', NULL, N'Austin', N'TX', N'98454'),
(13, N'5269 Oak Blvd', N'Apt 27', N'Austin', N'OR', N'98874'),
(14, N'3852 Oak St', NULL, N'Denver', N'CO', N'98538'),
(15, N'7107 Oak St', NULL, N'San Francisco', N'OR', N'98262'),
(16, N'7303 Elm Rd', NULL, N'San Francisco', N'OR', N'98262'),
(17, N'1854 Oak St', NULL, N'San Francisco', N'OR', N'98806'),
(18, N'5119 Cedar Ave', N'Apt 74', N'San Francisco', N'WA', N'98959'),
(19, N'7587 Maple Ave', NULL, N'Denver', N'OR', N'98432'),
(20, N'9306 Maple Blvd', NULL, N'Austin', N'CA', N'98863'),
(21, N'4295 Pine Ln', NULL, N'Austin', N'OR', N'98962'),
(22, N'2382 Oak St', NULL, N'Austin', N'TX', N'98135'),
(23, N'4960 Oak St', NULL, N'Portland', N'OR', N'98291'),
(24, N'5102 Oak Ln', N'Apt 53', N'Portland', N'TX', N'98126'),
(25, N'5536 Pine Blvd', N'Apt 69', N'Portland', N'TX', N'98362'),
(26, N'1465 Cedar Rd', NULL, N'Austin', N'OR', N'98123'),
(27, N'7528 Elm Rd', NULL, N'Austin', N'WA', N'98942'),
(28, N'9943 Pine Rd', N'Apt 78', N'San Francisco', N'CO', N'98101'),
(29, N'7547 Oak St', NULL, N'Seattle', N'TX', N'98723'),
(30, N'2846 Pine Ln', NULL, N'Portland', N'CO', N'98970'),
(31, N'7929 Maple Blvd', NULL, N'Seattle', N'OR', N'98864'),
(32, N'8993 Pine Blvd', NULL, N'Portland', N'WA', N'98932'),
(33, N'6346 Oak Ave', N'Apt 93', N'Denver', N'TX', N'98554'),
(34, N'7382 Oak Ln', N'Apt 34', N'San Francisco', N'TX', N'98728'),
(35, N'8677 Elm Blvd', NULL, N'Denver', N'CA', N'98479'),
(36, N'8613 Oak St', NULL, N'Austin', N'CA', N'98904'),
(37, N'6693 Pine St', NULL, N'San Francisco', N'CA', N'98367'),
(38, N'2683 Oak Rd', NULL, N'Austin', N'CO', N'98598'),
(39, N'8261 Oak Blvd', NULL, N'Seattle', N'CA', N'98852'),
(40, N'8157 Cedar Ln', NULL, N'Portland', N'WA', N'98936'),
(41, N'9853 Oak Rd', NULL, N'San Francisco', N'OR', N'98650'),
(42, N'2039 Cedar Ln', NULL, N'San Francisco', N'WA', N'98947'),
(43, N'3976 Maple St', NULL, N'Portland', N'CA', N'98461'),
(44, N'1032 Maple Ave', N'Apt 78', N'Denver', N'CO', N'98452'),
(45, N'1944 Maple Ave', N'Apt 62', N'Denver', N'WA', N'98958'),
(46, N'3376 Maple Ave', N'Apt 73', N'Austin', N'CA', N'98212'),
(47, N'7733 Pine Rd', NULL, N'Portland', N'TX', N'98892'),
(48, N'449 Pine Blvd', N'Apt 42', N'Seattle', N'WA', N'98987'),
(49, N'6576 Pine Ln', NULL, N'Portland', N'CA', N'98636'),
(50, N'7647 Cedar Rd', N'Apt 64', N'Austin', N'OR', N'98327'),
(51, N'6085 Maple Ln', NULL, N'Portland', N'CO', N'98109'),
(52, N'3952 Elm Ave', NULL, N'San Francisco', N'WA', N'98170'),
(53, N'3561 Elm Blvd', NULL, N'Portland', N'CO', N'98743'),
(54, N'8069 Elm Ave', N'Apt 58', N'San Francisco', N'TX', N'98484'),
(55, N'3984 Oak Blvd', NULL, N'Austin', N'OR', N'98140'),
(56, N'3490 Elm St', N'Apt 50', N'San Francisco', N'WA', N'98764'),
(57, N'2042 Elm Blvd', NULL, N'Denver', N'CA', N'98294'),
(58, N'8965 Oak Ave', NULL, N'Denver', N'CO', N'98178'),
(59, N'3006 Elm Rd', NULL, N'Seattle', N'CO', N'98850'),
(60, N'9836 Maple Ln', NULL, N'Denver', N'CA', N'98841'),
(61, N'8936 Cedar Ave', NULL, N'Seattle', N'CO', N'98470'),
(62, N'5493 Elm Blvd', N'Apt 28', N'Denver', N'TX', N'98436'),
(63, N'4071 Elm Rd', N'Apt 41', N'San Francisco', N'TX', N'98728'),
(64, N'3124 Cedar Ln', NULL, N'Seattle', N'WA', N'98432'),
(65, N'2485 Oak St', N'Apt 29', N'Denver', N'CA', N'98952'),
(66, N'8116 Pine Rd', NULL, N'San Francisco', N'OR', N'98889'),
(67, N'7385 Cedar Ave', NULL, N'Seattle', N'CA', N'98565'),
(68, N'5682 Oak St', NULL, N'San Francisco', N'WA', N'98987'),
(69, N'6361 Elm Blvd', NULL, N'Denver', N'OR', N'98327'),
(70, N'4488 Pine Ave', N'Apt 99', N'Seattle', N'OR', N'98575'),
(71, N'2536 Pine St', N'Apt 100', N'Austin', N'WA', N'98789'),
(72, N'3680 Maple Rd', NULL, N'Portland', N'WA', N'98292'),
(73, N'7178 Oak Blvd', NULL, N'San Francisco', N'CA', N'98369'),
(74, N'2179 Pine Ave', NULL, N'San Francisco', N'CA', N'98641'),
(75, N'8212 Oak Ave', N'Apt 52', N'Denver', N'WA', N'98419'),
(76, N'9857 Maple Rd', NULL, N'Portland', N'TX', N'98479'),
(77, N'163 Cedar Ave', NULL, N'Seattle', N'CA', N'98859'),
(78, N'4502 Cedar Blvd', N'Apt 2', N'Seattle', N'CO', N'98650'),
(79, N'9957 Pine Rd', NULL, N'Portland', N'CO', N'98248'),
(80, N'4846 Cedar Rd', N'Apt 70', N'Seattle', N'OR', N'98538'),
(81, N'2469 Oak Rd', NULL, N'Seattle', N'TX', N'98697'),
(82, N'3410 Cedar Ave', NULL, N'Denver', N'TX', N'98789'),
(83, N'8751 Cedar St', N'Apt 99', N'Denver', N'OR', N'98624'),
(84, N'5948 Pine Ln', NULL, N'Austin', N'CA', N'98182'),
(85, N'4233 Pine Ln', NULL, N'Seattle', N'CA', N'98622'),
(86, N'3656 Pine Rd', NULL, N'Denver', N'WA', N'98396'),
(87, N'8516 Elm Blvd', NULL, N'Portland', N'OR', N'98273'),
(88, N'6112 Maple Blvd', NULL, N'San Francisco', N'OR', N'98827'),
(89, N'1920 Oak Ave', N'Apt 39', N'Austin', N'OR', N'98853'),
(90, N'9713 Pine Ave', NULL, N'Seattle', N'CA', N'98288'),
(91, N'6745 Oak Ln', NULL, N'San Francisco', N'TX', N'98997');

MERGE [Org].[Address] T
USING (SELECT * FROM @AddressStaging) S
    ON T.AddressID = S.AddressID
WHEN MATCHED AND (
    T.AddressLineOne <> S.AddressLineOne
    OR T.AddressLineTwo <> S.AddressLineTwo
    OR T.CityName <> S.CityName
    OR T.State <> S.State
    OR T.ZipCode <> S.ZipCode
) THEN
    UPDATE SET
        AddressLineOne = S.AddressLineOne,
        AddressLineTwo = S.AddressLineTwo,
        CityName = S.CityName,
        [State] = S.State,
        ZipCode = S.ZipCode
WHEN NOT MATCHED THEN
    INSERT(AddressLineOne, AddressLineTwo, CityName, [State], ZipCode)
    VALUES(S.AddressLineOne, S.AddressLineTwo, S.CityName, S.State, S.ZipCode);
