DECLARE @SalaryEmployeeStaging TABLE
(
    EmployeeID INT NOT NULL PRIMARY KEY,
    SalaryID INT NOT NULL,
    PaidTimeOffHours INT NOT NULL,
    SickHours INT NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b & Gemini
-- SalaryEmployee records for all salary employees (EmployeeTypeID=1)
-- Only employees with salary employment type receive salary data
-- Higher positions receive higher salaries as per the salary structure

INSERT @SalaryEmployeeStaging(EmployeeID, SalaryID, PaidTimeOffHours, SickHours) VALUES
(1, 1, 141, 77),
(2, 2, 151, 90),
(3, 3, 107, 82),
(4, 4, 179, 86),
(5, 5, 137, 70),
(6, 6, 131, 81),
(7, 7, 150, 81),
(8, 8, 120, 77),
(9, 9, 91, 82),
(10, 10, 150, 81),
(11, 11, 154, 89),
(12, 12, 128, 45),
(13, 13, 173, 58),
(14, 14, 96, 51),
(15, 15, 197, 44),
(16, 16, 90, 60),
(17, 17, 139, 72),
(18, 18, 164, 97),
(19, 19, 91, 41),
(20, 20, 132, 95),
(21, 21, 89, 100),
(22, 22, 194, 45),
(23, 23, 94, 93),
(24, 24, 158, 92),
(25, 25, 153, 40),
(29, 29, 166, 46),
(30, 30, 99, 67),
(31, 31, 106, 92),
(32, 32, 160, 92),
(33, 33, 144, 88),
(34, 34, 88, 80),
(35, 35, 161, 71),
(36, 36, 136, 44),
(37, 37, 117, 94),
(38, 38, 135, 77),
(39, 39, 165, 77),
(40, 40, 142, 91),
(41, 41, 141, 100),
(42, 42, 164, 70),
(43, 43, 198, 78),
(44, 44, 122, 47),
(45, 45, 144, 50),
(46, 46, 131, 92),
(47, 47, 197, 77),
(49, 49, 142, 92),
(50, 50, 87, 53),
(51, 51, 115, 82),
(53, 53, 166, 82),
(54, 54, 98, 80),
(55, 55, 165, 100),
(56, 56, 176, 91),
(58, 58, 97, 84),
(59, 59, 95, 68),
(60, 60, 185, 51),
(61, 61, 180, 45),
(62, 62, 167, 63),
(63, 63, 155, 88),
(64, 64, 197, 63),
(65, 65, 158, 78),
(66, 66, 148, 94),
(67, 67, 84, 48),
(68, 68, 105, 90),
(69, 69, 129, 98),
(70, 70, 199, 85),
(71, 71, 160, 49),
(72, 72, 196, 45),
(73, 73, 150, 81),
(74, 74, 113, 58),
(75, 75, 130, 96),
(76, 76, 97, 46),
(77, 77, 165, 61),
(78, 78, 188, 48),
(79, 79, 152, 97),
(80, 80, 135, 91),
(81, 81, 98, 62),
(82, 82, 151, 65),
(83, 83, 171, 68),
(84, 84, 96, 95),
(85, 85, 162, 88),
(86, 86, 163, 96),
(87, 87, 123, 84),
(88, 88, 196, 88),
(89, 89, 138, 58),
(90, 90, 180, 90),
(91, 91, 176, 91);


MERGE [Org].SalaryEmployee T
USING (SELECT * FROM @SalaryEmployeeStaging) S
    ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.SalaryID <> S.SalaryID
    OR T.PaidTimeOffHours <> S.PaidTimeOffHours
    OR T.SickHours <> S.SickHours
) THEN
    UPDATE SET
        SalaryID = S.SalaryID,
        PaidTimeOffHours = S.PaidTimeOffHours,
        SickHours = S.SickHours
WHEN NOT MATCHED THEN
    INSERT(EmployeeID, SalaryID, PaidTimeOffHours, SickHours)
    VALUES(S.EmployeeID, S.SalaryID, S.PaidTimeOffHours, S.SickHours);
