DECLARE @DepEmpRoleStaging TABLE
(
    RoleID INT NOT NULL,
    DepartmentID INT NOT NULL,
    EmployeeID INT NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @DepEmpRoleStaging(RoleID, DepartmentID, EmployeeID)
VALUES
-- CEO (reports to NULL, is in all departments)
(12, 1, 1),
(12, 2, 1),
(12, 3, 1),
(12, 4, 1),
(12, 5, 1),
-- HR Department Executive (reports to CEO, HR Department)
(11, 2, 2),
-- Finance Department Executive (reports to CEO, Finance Department)
(10, 3, 3),
-- Sales Department Executive (reports to CEO, Sales Department)
(6, 4, 4),
-- Marketing Department Executive (reports to CEO, Marketing Department)
(6, 5, 5),
-- Engineering Department Executive (reports to CEO, Engineering Department)
(9, 1, 6),
-- HR Director (reports to HR Executive, HR Department)
(8, 2, 7),
-- Finance Director (reports to Finance Executive, Finance Department)
(8, 3, 8),
-- Sales Director (reports to Sales Executive, Sales Department)
(8, 4, 9),
-- Marketing Director (reports to Marketing Executive, Marketing Department)
(8, 5, 10),
-- Engineering Director (reports to Engineering Executive, Engineering Department)
(8, 1, 11),
-- HR Manager (reports to HR Director, HR Department)
(7, 2, 12),
-- Finance Manager (reports to Finance Director, Finance Department)
(7, 3, 13),
-- Sales Manager (reports to Sales Director, Sales Department)
(7, 4, 14),
-- Marketing Manager (reports to Marketing Director, Marketing Department)
(7, 5, 15),
-- Engineering Manager (reports to Engineering Director, Engineering Department)
(7, 1, 16),

-- HR Staff (reports to HR Manager, HR Department)
(1, 2, 17), (6, 2, 18), (1, 2, 19), (6, 2, 20), (1, 2, 21), (6, 2, 22), (1, 2, 23), (6, 2, 24), (1, 2, 25), (6, 2, 26),
-- Finance Staff (reports to Finance Manager, Finance Department)
(6, 3, 27), (1, 3, 28), (6, 3, 29), (1, 3, 30), (6, 3, 31), (1, 3, 32), (6, 3, 33), (1, 3, 34), (6, 3, 35), (1, 3, 36),
-- Sales Staff (reports to Sales Manager, Sales Department)
(1, 4, 37), (6, 4, 38), (1, 4, 39), (6, 4, 40), (1, 4, 41), (6, 4, 42), (1, 4, 43), (6, 4, 44), (1, 4, 45), (6, 4, 46),
-- Marketing Staff (reports to Marketing Manager, Marketing Department)
(6, 5, 47), (1, 5, 48), (6, 5, 49), (1, 5, 50), (6, 5, 51), (1, 5, 52), (6, 5, 53), (1, 5, 54), (6, 5, 55), (1, 5, 56),
-- Engineering Staff (reports to Engineering Manager, Engineering Department)
-- 2 Senior Engineers (RoleID=5)
(5, 1, 57), (5, 1, 58),
-- 2 Developer III (RoleID=4)
(4, 1, 59), (4, 1, 60),
-- 2 Developer II (RoleID=3)
(3, 1, 61), (3, 1, 62),
-- 2 Developer I (RoleID=2)
(2, 1, 63), (2, 1, 64),
-- 2 Interns (RoleID=1)
(1, 1, 65), (1, 1, 66);

MERGE Org.DepEmpRole T
USING (SELECT * FROM @DepEmpRoleStaging) S
    ON T.RoleID = S.RoleID
    AND T.DepartmentID = S.DepartmentID
    AND T.EmployeeID = S.EmployeeID
WHEN NOT MATCHED THEN
    INSERT(RoleID, DepartmentID, EmployeeID)
    VALUES(S.RoleID, S.DepartmentID, S.EmployeeID);
