DECLARE @AddressStaging TABLE
(
    AddressID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    AddressLineOne NVARCHAR(255) NOT NULL,
    AddressLineTwo NVARCHAR(255),
    CityName NVARCHAR(100) NOT NULL,
    State NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(20) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @AddressStaging(AddressLineOne, AddressLineTwo, CityName, State, ZipCode)
VALUES
(N'123 Main Street', N'Apt 4B', N'Springfield', N'IL', N'62701'),
(N'456 Oak Avenue', NULL, N'Chicago', N'IL', N'60601'),
(N'789 Pine Road', N'Suite 200', N'Peoria', N'IL', N'61601'),
(N'321 Elm Street', NULL, N'Rockford', N'IL', N'61101'),
(N'654 Maple Drive', N'Unit 12', N'Naperville', N'IL', N'60540'),
(N'987 Cedar Lane', NULL, N'Evanston', N'IL', N'60201'),
(N'147 Birch Court', N'Floor 3', N'Arlington Heights', N'IL', N'60004'),
(N'258 Walnut Street', NULL, N'Elgin', N'IL', N'60120'),
(N'369 Cherry Boulevard', N'Building C', N'Bloomington', N'IL', N'61701'),
(N'741 Ash Avenue', NULL, N'Normal', N'IL', N'61790');

MERGE Org.Address T
USING (SELECT * FROM @AddressStaging) S ON T.AddressID = S.AddressID
WHEN MATCHED AND (
    T.AddressLineOne <> S.AddressLineOne
    OR T.AddressLineTwo <> S.AddressLineTwo
    OR T.CityName <> S.CityName
    OR T.State <> S.State
    OR T.ZipCode <> S.ZipCode
) THEN
    UPDATE SET
        AddressLineOne = S.AddressLineOne,
        AddressLineTwo = S.AddressLineTwo,
        CityName = S.CityName,
        State = S.State,
        ZipCode = S.ZipCode
WHEN NOT MATCHED THEN
    INSERT(AddressLineOne, AddressLineTwo, CityName, State, ZipCode)
    VALUES(S.AddressLineOne, S.AddressLineTwo, S.CityName, S.State, S.ZipCode);
