DECLARE @DepEmpRoleStaging TABLE
(
    RoleID INT NOT NULL,
    DepartmentID INT NOT NULL,
    EmployeeID INT NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @DepEmpRoleStaging(RoleID, DepartmentID, EmployeeID)
VALUES
-- CEO in all departments
(1, 1, 1),  -- CEO in Engineering
(1, 2, 1),  -- CEO in HR
(1, 3, 1),  -- CEO in Finance
(1, 4, 1),  -- CEO in Sales
(1, 5, 1),  -- CEO in Marketing
-- CTO in Engineering
(2, 1, 2),
-- CFO in Finance
(3, 3, 3),
-- HR Manager in HR
(7, 2, 4),
-- Sales Manager in Sales
(1, 4, 5),
-- Marketing Manager in Marketing
(1, 5, 6),
-- Senior Engineers in Engineering
(1, 1, 7),
(1, 1, 8),
(1, 1, 9),
(1, 1, 10);

MERGE Org.DepEmpRole T
USING (SELECT * FROM @DepEmpRoleStaging) S
    ON T.RoleID = S.RoleID
    AND T.DepartmentID = S.DepartmentID
    AND T.EmployeeID = S.EmployeeID
WHEN NOT MATCHED THEN
    INSERT(RoleID, DepartmentID, EmployeeID)
    VALUES(S.RoleID, S.DepartmentID, S.EmployeeID);
