DECLARE @EmployeeTypeStaging TABLE
(
    [Name] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(255) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @EmployeeTypeStaging([Name], [Description])
VALUES
(N'Salary', N'Full-time salaried employee'),
(N'Hourly', N'Hourly paid employee');

MERGE Org.EmployeeType T
USING (SELECT * FROM @EmployeeTypeStaging) S ON T.Name = S.Name
WHEN MATCHED AND (
    T.Description <> S.Description
) THEN
    UPDATE SET [Description] = S.Description
WHEN NOT MATCHED THEN
    INSERT([Name], [Description])
    VALUES(S.Name, S.Description);
