DECLARE @DepartmentStaging TABLE
(
    CompanyID INT NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [Description] NVARCHAR(255)
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b & Gemini
INSERT @DepartmentStaging(CompanyID, [Name], [Description]) VALUES
(1, N'Executive', N'Executive Department'),
(1, N'Engineering', N'Engineering Department'),
(1, N'Finance', N'Finance Department'),
(1, N'Human Resources', N'Human Resources Department'),
(1, N'Sales', N'Sales Department'),
(2, N'Executive', N'Executive Department'),
(2, N'Engineering', N'Engineering Department'),
(2, N'Finance', N'Finance Department'),
(2, N'Human Resources', N'Human Resources Department'),
(2, N'Sales', N'Sales Department'),
(3, N'Executive', N'Executive Department'),
(3, N'Engineering', N'Engineering Department'),
(3, N'Finance', N'Finance Department'),
(3, N'Human Resources', N'Human Resources Department'),
(3, N'Sales', N'Sales Department');

MERGE [Org].Department T
USING (SELECT * FROM @DepartmentStaging) S
    ON T.CompanyID = S.CompanyID
    AND T.[Name] = S.[Name]
WHEN MATCHED AND (
    T.[Name] <> S.[Name]
    OR T.Description <> S.Description
) THEN
    UPDATE SET [Name] = S.[Name], [Description] = S.Description
WHEN NOT MATCHED THEN
    INSERT(CompanyID, [Name], [Description])
    VALUES(S.CompanyID, S.[Name], S.Description);
