DECLARE @DepEmpRoleStaging TABLE
(
    RoleID INT NOT NULL,
    DepartmentID INT NOT NULL,
    EmployeeID INT NOT NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @DepEmpRoleStaging(RoleID, DepartmentID, EmployeeID, StartDate, EndDate)
VALUES
-- CEO in all departments
(1, 2, 1, '2020-01-15T00:00:00', NULL),  -- CEO in Engineering
(1, 4, 1, '2020-01-15T00:00:00', NULL),  -- CEO in HR
(1, 3, 1, '2020-01-15T00:00:00', NULL),  -- CEO in Finance
(1, 6, 1, '2020-01-15T00:00:00', NULL),  -- CEO in Sales
(1, 5, 1, '2020-01-15T00:00:00', NULL),  -- CEO in Marketing
-- CTO in Engineering
(2, 2, 2, '2018-03-20T00:00:00', NULL),
-- CFO in Finance
(3, 3, 3, '2019-06-10T00:00:00', NULL),
-- HR Manager in HR
(7, 4, 4, '2017-11-05T00:00:00', NULL),
-- Sales Manager in Sales
(1, 6, 5, '2019-02-28T00:00:00', NULL),
-- Marketing Manager in Marketing
(1, 5, 6, '2020-08-15T00:00:00', NULL),
-- Senior Engineers in Engineering
(1, 2, 7, '2021-01-10T00:00:00', NULL),
(1, 2, 8, '2021-03-15T00:00:00', NULL),
(1, 2, 9, '2021-05-20T00:00:00', NULL),
(1, 2, 10, '2021-07-01T00:00:00', NULL);

MERGE Org.DepEmpRole T
USING (SELECT * FROM @DepEmpRoleStaging) S
    ON T.RoleID = S.RoleID
    AND T.DepartmentID = S.DepartmentID
    AND T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.StartDate <> S.StartDate OR
    T.EndDate <> S.EndDate
) THEN
    UPDATE SET StartDate = S.StartDate, EndDate = S.EndDate
WHEN NOT MATCHED THEN
    INSERT(RoleID, DepartmentID, EmployeeID, StartDate, EndDate)
    VALUES(S.RoleID, S.DepartmentID, S.EmployeeID, S.StartDate, S.EndDate);
