DECLARE @PersonStaging TABLE
(
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(255) NOT NULL,
    [Phone] NVARCHAR(50)
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @PersonStaging([FirstName], [LastName], [Email], [Phone])
VALUES
(N'John', N'Smith', N'john.smith@techcorp.com', N'+1-555-0101'),
(N'Jane', N'Doe', N'jane.doe@techcorp.com', N'+1-555-0102'),
(N'Robert', N'Johnson', N'robert.johnson@techcorp.com', N'+1-555-0103'),
(N'Michael', N'Williams', N'michael.williams@techcorp.com', N'+1-555-0104'),
(N'Emily', N'Brown', N'emily.brown@techcorp.com', N'+1-555-0105'),
(N'David', N'Jones', N'david.jones@techcorp.com', N'+1-555-0106'),
(N'Sarah', N'Garcia', N'sarah.garcia@techcorp.com', N'+1-555-0107'),
(N'James', N'Miller', N'james.miller@techcorp.com', N'+1-555-0108'),
(N'Patricia', N'Davis', N'patricia.davis@techcorp.com', N'+1-555-0109'),
(N'Christopher', N'Rodriguez', N'christopher.rodriguez@techcorp.com', N'+1-555-0110');

MERGE Org.Person T
USING (SELECT * FROM @PersonStaging) S ON T.Email = S.Email
WHEN MATCHED AND (
    T.FirstName <> S.FirstName
    OR T.LastName <> S.LastName
    OR T.Phone <> S.Phone
) THEN
    UPDATE SET FirstName = S.FirstName, LastName = S.LastName, Phone = S.Phone
WHEN NOT MATCHED THEN
    INSERT([FirstName], [LastName], [Email], [Phone])
    VALUES(S.FirstName, S.LastName, S.Email, S.Phone);
