DECLARE @HourlyEmployeeStaging TABLE
(
    EmployeeID INT NOT NULL,
    HourlyPay DECIMAL(18, 2) NOT NULL,
    MaxHoursPerWeek INT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @HourlyEmployeeStaging(EmployeeID, HourlyPay, MaxHoursPerWeek)
VALUES
-- All Interns (RoleID=1) converted to hourly
-- HR Interns
(17, 15.00, 35), (19, 15.50, 32), (21, 16.00, 38), (23, 16.50, 30), (25, 17.00, 40),
-- Finance Interns
(28, 15.00, 28), (30, 15.50, 33), (32, 16.00, 36), (34, 16.50, 29), (36, 17.00, 42),
-- Sales Interns
(37, 15.00, 37), (39, 15.50, 31), (41, 16.00, 39), (43, 16.50, 27), (45, 17.00, 41),
-- Marketing Interns
(48, 15.00, 34), (50, 15.50, 30), (52, 16.00, 38), (54, 16.50, 26), (56, 17.00, 43),
-- Engineering Interns
(65, 15.00, NULL), (66, 15.50, NULL),
-- ~10% of Members (RoleID=6) converted to hourly (3 members from Finance)
(27, 20.00, NULL), (31, 20.50, NULL), (35, 21.00, NULL);

MERGE Org.HourlyEmployee T
USING (SELECT * FROM @HourlyEmployeeStaging) S ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (T.HourlyPay <> S.HourlyPay OR T.MaxHoursPerWeek <> S.MaxHoursPerWeek
) THEN
    UPDATE SET
        HourlyPay = S.HourlyPay,
        MaxHoursPerWeek = S.MaxHoursPerWeek
WHEN NOT MATCHED THEN
    INSERT(EmployeeID, HourlyPay, MaxHoursPerWeek)
    VALUES(S.EmployeeID, S.HourlyPay, S.MaxHoursPerWeek);
