DECLARE @SalaryEmployeeStaging TABLE
(
    EmployeeID INT NOT NULL PRIMARY KEY,
    PaidTimeOffHours INT NOT NULL,
    SickHours INT NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
-- SalaryEmployee records for all salary employees (EmployeeTypeID=1)
-- Only employees with salary employment type receive salary data
-- Higher positions receive higher salaries as per the salary structure

INSERT INTO @SalaryEmployeeStaging (EmployeeID, PaidTimeOffHours, SickHours)
VALUES 
-- EXECUTIVES (EmployeeTypeID=1) - PersonIDs 1-6
-- CEO (PersonID=1)
(1, 20, 40),
-- HR Department Executive (PersonID=2)
(2, 20, 40),
-- Finance Department Exec
(3, 20, 40),
-- Sales Department Executive
(4, 20, 40),
-- Marketing Department Executive
(5, 20, 40),
-- Engineering Department Executive
(6, 20, 40),

-- DIRECTORS (EmployeeTypeID=1) - PersonIDs 7-11
-- HR Director (PersonID=7)
(7, 15, 30),
-- Finance Director (PersonID=8)
(8, 15, 30),
-- Sales Director (PersonID=9)
(9, 15, 30),
-- Marketing Director (PersonID=10)
(10, 15, 30),
-- Engineering Director (PersonID=11)
(11, 15, 30),

-- MANAGERS (EmployeeTypeID=1) - PersonIDs 12-16
-- HR Manager (PersonID=12)
(12, 12, 24),
-- Finance Manager (PersonID=13)
(13, 12, 24),
-- Sales Manager (PersonID=14)
(14, 12, 24),
-- Marketing Manager (PersonID=15)
(15, 12, 24),
-- Engineering Manager (PersonID=16)
(16, 12, 24),

-- HR STAFF (EmployeeTypeID=1) - PersonIDs 17-26
-- HR Staff (PersonID=17)
(17, 10, 20),
-- HR Staff (PersonID=18)
(18, 10, 20),
-- HR Staff (PersonID=19)
(19, 10, 20),
-- HR Staff (PersonID=20)
(20, 10, 20),
-- HR Staff (PersonID=21) - Hourly employee (EmployeeTypeID=2), excluded from salary data
(22, 10, 20),
-- HR Staff (PersonID=23) - Hourly employee (EmployeeTypeID=2), excluded from salary data
(24, 10, 20),
-- HR Staff (PersonID=25) - Hourly employee (EmployeeTypeID=2), excluded from salary data
(26, 10, 20),

-- FINANCE STAFF (EmployeeTypeID=1) - PersonIDs 27-36
-- Finance Staff (PersonID=27)
(27, 10, 20),
-- Finance Staff (PersonID=28)
(28, 10, 20),
-- Finance Staff (PersonID=29)
(29, 10, 20),
-- Finance Staff (PersonID=30)
(30, 10, 20),
-- Finance Staff (PersonID=31)
(31, 10, 20),
-- Finance Staff (PersonID=32)
(32, 10, 20),
-- Finance Staff (PersonID=33)
(33, 10, 20),
-- Finance Staff (PersonID=34)
(34, 10, 20),
-- Finance Staff (PersonID=35)
(35, 10, 20),
-- Finance Staff (PersonID=36)
(36, 10, 20),

-- SALES STAFF (EmployeeTypeID=1) - PersonIDs 37-46
-- Sales Staff (PersonID=37)
(37, 10, 20),
-- Sales Staff (PersonID=38)
(38, 10, 20),
-- Sales Staff (PersonID=39)
(39, 10, 20),
-- Sales Staff (PersonID=40)
(40, 10, 20),
-- Sales Staff (PersonID=41)
(41, 10, 20),
-- Sales Staff (PersonID=42)
(42, 10, 20),
-- Sales Staff (PersonID=43)
(43, 10, 20),
-- Sales Staff (PersonID=44)
(44, 10, 20),
-- Sales Staff (PersonID=45)
(45, 10, 20),
-- Sales Staff (PersonID=46)
(46, 10, 20),

-- MARKETING STAFF (EmployeeTypeID=1) - PersonIDs 47-56
-- Marketing Staff (PersonID=47)
(47, 10, 20),
-- Marketing Staff (PersonID=48)
(48, 10, 20),
-- Marketing Staff (PersonID=49)
(49, 10, 20),
-- Marketing Staff (PersonID=50)
(50, 10, 20),
-- Marketing Staff (PersonID=51)
(51, 10, 20),
-- Marketing Staff (PersonID=52)
(52, 10, 20),
-- Marketing Staff (PersonID=53)
(53, 10, 20),
-- Marketing Staff (PersonID=54)
(54, 10, 20),
-- Marketing Staff (PersonID=55)
(55, 10, 20),
-- Marketing Staff (PersonID=56)
(56, 10, 20),

-- ENGINEERING STAFF (EmployeeTypeID=1) - PersonIDs 57-66
-- Engineering Staff (PersonID=57)
(57, 10, 20),
-- Engineering Staff (PersonID=58)
(58, 10, 20),
-- Engineering Staff (PersonID=59)
(59, 10, 20),
-- Engineering Staff (PersonID=60)
(60, 10, 20),
-- Engineering Staff (PersonID=61)
(61, 10, 20),
-- Engineering Staff (PersonID=62)
(62, 10, 20);
-- Engineering Staff (PersonID=63) - Hourly employee (EmployeeTypeID=2), excluded from salary data
-- Engineering Staff (PersonID=64) - Hourly employee (EmployeeTypeID=2), excluded from salary data
-- Engineering Staff (PersonID=65) - Hourly employee (EmployeeTypeID=2), excluded from salary data
-- Engineering Staff (PersonID=66) - Hourly employee (EmployeeTypeID=2), excluded from salary data

MERGE Org.SalaryEmployee T
USING (SELECT * FROM @SalaryEmployeeStaging) S ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.PaidTimeOffHours <> S.PaidTimeOffHours OR
    T.SickHours <> S.SickHours
) THEN
    UPDATE SET 
        PaidTimeOffHours = S.PaidTimeOffHours,
        SickHours = S.SickHours
WHEN NOT MATCHED THEN
    INSERT(EmployeeID, PaidTimeOffHours, SickHours)
    VALUES(S.EmployeeID, S.PaidTimeOffHours, S.SickHours);
