DECLARE @RoleStaging TABLE
(
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(255) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @RoleStaging(Name, Description)
VALUES
(N'Member', N'Regular team member'),
(N'Manager', N'Department manager'),
(N'Director', N'Senior manager'),
(N'CEO', N'Chief Executive Officer'),
(N'CTO', N'Chief Technology Officer'),
(N'CFO', N'Chief Financial Officer'),
(N'HR Manager', N'Human Resources Manager');

MERGE Org.Role T
USING (SELECT * FROM @RoleStaging) S ON T.Name = S.Name
WHEN MATCHED AND (
    T.Description <> S.Description
) THEN
    UPDATE SET Description = S.Description
WHEN NOT MATCHED THEN
    INSERT(Name, Description)
    VALUES(S.Name, S.Description);
