-- Data generated by RooCode - Local qwen/qwen3.5-9b via script

DECLARE @PersonStaging TABLE
(
    PersonID INT NOT NULL,
    AddressID INT NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50)
);

INSERT @PersonStaging(PersonID, AddressID, FirstName, LastName, Email, Phone) VALUES
(1, 1, N'Thomas', N'Moore', N'thomas.moore1@company.com', N'555-863-9104'),
(2, 2, N'Sandra', N'Rivera', N'sandra.rivera2@company.com', N'555-874-4818'),
(3, 3, N'William', N'Perez', N'william.perez3@company.com', N'555-974-4892'),
(4, 4, N'Mark', N'Walker', N'mark.walker4@company.com', N'555-628-1628'),
(5, 5, N'Barbara', N'Wright', N'barbara.wright5@company.com', N'555-465-8822'),
(6, 6, N'Stephanie', N'Clark', N'stephanie.clark6@company.com', N'555-692-1631'),
(7, 7, N'John', N'Wilson', N'john.wilson7@company.com', N'555-723-3148'),
(8, 8, N'Kevin', N'Martinez', N'kevin.martinez8@company.com', N'555-163-7736'),
(9, 9, N'Steven', N'Harris', N'steven.harris9@company.com', N'555-654-2299'),
(10, 10, N'Patricia', N'Nguyen', N'patricia.nguyen10@company.com', N'555-324-7702'),
(11, 11, N'Stephanie', N'Jackson', N'stephanie.jackson11@company.com', N'555-272-5123'),
(12, 12, N'Kenneth', N'Lopez', N'kenneth.lopez12@company.com', N'555-227-2361'),
(13, 13, N'Carol', N'Flores', N'carol.flores13@company.com', N'555-960-1469'),
(14, 14, N'Sandra', N'Perez', N'sandra.perez14@company.com', N'555-765-8045'),
(15, 15, N'Jennifer', N'Walker', N'jennifer.walker15@company.com', N'555-599-8828'),
(16, 16, N'Kenneth', N'Perez', N'kenneth.perez16@company.com', N'555-942-7538'),
(17, 17, N'Elizabeth', N'Nelson', N'elizabeth.nelson17@company.com', N'555-797-9888'),
(18, 18, N'Elizabeth', N'Clark', N'elizabeth.clark18@company.com', N'555-196-6441'),
(19, 19, N'Margaret', N'Campbell', N'margaret.campbell19@company.com', N'555-668-3096'),
(20, 20, N'Kimberly', N'Miller', N'kimberly.miller20@company.com', N'555-981-9503'),
(21, 21, N'Steven', N'Walker', N'steven.walker21@company.com', N'555-286-5886'),
(22, 22, N'David', N'Clark', N'david.clark22@company.com', N'555-474-7249'),
(23, 23, N'Daniel', N'Jackson', N'daniel.jackson23@company.com', N'555-398-1313'),
(24, 24, N'John', N'Green', N'john.green24@company.com', N'555-435-1732'),
(25, 25, N'Robert', N'Smith', N'robert.smith25@company.com', N'555-699-9252'),
(26, 26, N'Elizabeth', N'Nguyen', N'elizabeth.nguyen26@company.com', N'555-421-8432'),
(27, 27, N'Linda', N'Garcia', N'linda.garcia27@company.com', N'555-857-5941'),
(28, 28, N'Margaret', N'Rodriguez', N'margaret.rodriguez28@company.com', N'555-926-4906'),
(29, 29, N'Anthony', N'Wright', N'anthony.wright29@company.com', N'555-163-4006'),
(30, 30, N'Jessica', N'Taylor', N'jessica.taylor30@company.com', N'555-528-2819'),
(31, 31, N'Sarah', N'Young', N'sarah.young31@company.com', N'555-948-8040'),
(32, 32, N'Deborah', N'Young', N'deborah.young32@company.com', N'555-292-4777'),
(33, 33, N'Nancy', N'Campbell', N'nancy.campbell33@company.com', N'555-927-8498'),
(34, 34, N'John', N'Martinez', N'john.martinez34@company.com', N'555-690-5221'),
(35, 35, N'Kevin', N'Carter', N'kevin.carter35@company.com', N'555-951-3731'),
(36, 36, N'Michelle', N'Thomas', N'michelle.thomas36@company.com', N'555-588-2106'),
(37, 37, N'Kevin', N'Davis', N'kevin.davis37@company.com', N'555-232-7224'),
(38, 38, N'Elizabeth', N'Anderson', N'elizabeth.anderson38@company.com', N'555-699-5551'),
(39, 39, N'Sandra', N'Jones', N'sandra.jones39@company.com', N'555-837-4183'),
(40, 40, N'Amanda', N'Hall', N'amanda.hall40@company.com', N'555-684-9075'),
(41, 41, N'Linda', N'Wilson', N'linda.wilson41@company.com', N'555-626-9760'),
(42, 42, N'Margaret', N'Jones', N'margaret.jones42@company.com', N'555-811-7785'),
(43, 43, N'Richard', N'Martin', N'richard.martin43@company.com', N'555-795-4407'),
(44, 44, N'Ashley', N'Rivera', N'ashley.rivera44@company.com', N'555-893-8219'),
(45, 45, N'Christopher', N'Roberts', N'christopher.roberts45@company.com', N'555-699-8176'),
(46, 46, N'Paul', N'Miller', N'paul.miller46@company.com', N'555-615-1949'),
(47, 47, N'David', N'Hall', N'david.hall47@company.com', N'555-588-1483'),
(48, 48, N'Steven', N'Torres', N'steven.torres48@company.com', N'555-485-7104'),
(49, 49, N'Daniel', N'Green', N'daniel.green49@company.com', N'555-483-4467'),
(50, 50, N'Elizabeth', N'Miller', N'elizabeth.miller50@company.com', N'555-248-7519'),
(51, 51, N'Michael', N'Rivera', N'michael.rivera51@company.com', N'555-812-7101'),
(52, 52, N'David', N'Hernandez', N'david.hernandez52@company.com', N'555-411-9409'),
(53, 53, N'Margaret', N'Adams', N'margaret.adams53@company.com', N'555-772-3003'),
(54, 54, N'Sarah', N'Harris', N'sarah.harris54@company.com', N'555-912-6468'),
(55, 55, N'Patricia', N'Lopez', N'patricia.lopez55@company.com', N'555-913-8768'),
(56, 56, N'John', N'Wilson', N'john.wilson56@company.com', N'555-116-6721'),
(57, 57, N'William', N'Williams', N'william.williams57@company.com', N'555-877-4656'),
(58, 58, N'Stephanie', N'Rivera', N'stephanie.rivera58@company.com', N'555-192-8351'),
(59, 59, N'Deborah', N'Smith', N'deborah.smith59@company.com', N'555-279-8112'),
(60, 60, N'Lisa', N'Baker', N'lisa.baker60@company.com', N'555-337-9685'),
(61, 61, N'Steven', N'Carter', N'steven.carter61@company.com', N'555-110-1117'),
(62, 62, N'Daniel', N'Jones', N'daniel.jones62@company.com', N'555-618-3520'),
(63, 63, N'Karen', N'Harris', N'karen.harris63@company.com', N'555-838-7601'),
(64, 64, N'John', N'Garcia', N'john.garcia64@company.com', N'555-242-1460'),
(65, 65, N'Michelle', N'Clark', N'michelle.clark65@company.com', N'555-707-5760'),
(66, 66, N'Ashley', N'Young', N'ashley.young66@company.com', N'555-930-4206'),
(67, 67, N'Michelle', N'Taylor', N'michelle.taylor67@company.com', N'555-929-2612'),
(68, 68, N'David', N'Sanchez', N'david.sanchez68@company.com', N'555-221-1324'),
(69, 69, N'Elizabeth', N'Rodriguez', N'elizabeth.rodriguez69@company.com', N'555-476-4814'),
(70, 70, N'Carol', N'Johnson', N'carol.johnson70@company.com', N'555-613-1034'),
(71, 71, N'Matthew', N'Jackson', N'matthew.jackson71@company.com', N'555-326-3463'),
(72, 72, N'Matthew', N'Nelson', N'matthew.nelson72@company.com', N'555-607-6229'),
(73, 73, N'Barbara', N'Young', N'barbara.young73@company.com', N'555-168-6741'),
(74, 74, N'William', N'Williams', N'william.williams74@company.com', N'555-349-6526'),
(75, 75, N'Nancy', N'Jones', N'nancy.jones75@company.com', N'555-917-6102'),
(76, 76, N'Sandra', N'Flores', N'sandra.flores76@company.com', N'555-516-5905'),
(77, 77, N'Kenneth', N'Taylor', N'kenneth.taylor77@company.com', N'555-408-6559'),
(78, 78, N'Jennifer', N'Taylor', N'jennifer.taylor78@company.com', N'555-519-9902'),
(79, 79, N'Joseph', N'Gonzales', N'joseph.gonzales79@company.com', N'555-715-6229'),
(80, 80, N'Joshua', N'Hernandez', N'joshua.hernandez80@company.com', N'555-237-3156'),
(81, 81, N'Richard', N'Wilson', N'richard.wilson81@company.com', N'555-917-9079'),
(82, 82, N'Sandra', N'Anderson', N'sandra.anderson82@company.com', N'555-961-2689'),
(83, 83, N'Donald', N'Smith', N'donald.smith83@company.com', N'555-287-5715'),
(84, 84, N'Betty', N'Adams', N'betty.adams84@company.com', N'555-987-9096'),
(85, 85, N'Matthew', N'White', N'matthew.white85@company.com', N'555-640-9440'),
(86, 86, N'Kimberly', N'Lewis', N'kimberly.lewis86@company.com', N'555-950-9604'),
(87, 87, N'Kevin', N'Jones', N'kevin.jones87@company.com', N'555-247-2584'),
(88, 88, N'Kenneth', N'Lee', N'kenneth.lee88@company.com', N'555-898-6752'),
(89, 89, N'Elizabeth', N'Johnson', N'elizabeth.johnson89@company.com', N'555-908-9313'),
(90, 90, N'Margaret', N'Sanchez', N'margaret.sanchez90@company.com', N'555-944-6004'),
(91, 91, N'Linda', N'Taylor', N'linda.taylor91@company.com', N'555-819-8505');

-- SET IDENTITY_INSERT Org.Person ON;
MERGE Org.Person T
USING (SELECT * FROM @PersonStaging) S ON T.PersonID = S.PersonID
WHEN MATCHED AND (
    T.AddressID <> S.AddressID OR
    T.FirstName <> S.FirstName OR
    T.LastName <> S.LastName OR
    T.Email <> S.Email OR
    T.Phone <> S.Phone
) THEN UPDATE SET
    AddressID = S.AddressID,
    FirstName = S.FirstName,
    LastName = S.LastName,
    Email = S.Email,
    Phone = S.Phone
WHEN NOT MATCHED THEN
    INSERT(AddressID, FirstName, LastName, Email, Phone)
    VALUES(S.AddressID, S.FirstName, S.LastName, S.Email, S.Phone);
-- SET IDENTITY_INSERT Org.Person OFF;
