DECLARE @HourlyEmployeeStaging TABLE
(
    [EmployeeID] INT NOT NULL,
    [EmployeeTypeID] INT NOT NULL,
    [HourlyPay] DECIMAL(18, 2) NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @HourlyEmployeeStaging([EmployeeID], [EmployeeTypeID], [HourlyPay])
VALUES
-- All Interns (RoleID=1) converted to hourly
-- HR Interns
(17, 2, 15.00), (19, 2, 15.50), (21, 2, 16.00), (23, 2, 16.50), (25, 2, 17.00),
-- Finance Interns
(28, 2, 15.00), (30, 2, 15.50), (32, 2, 16.00), (34, 2, 16.50), (36, 2, 17.00),
-- Sales Interns
(37, 2, 15.00), (39, 2, 15.50), (41, 2, 16.00), (43, 2, 16.50), (45, 2, 17.00),
-- Marketing Interns
(48, 2, 15.00), (50, 2, 15.50), (52, 2, 16.00), (54, 2, 16.50), (56, 2, 17.00),
-- Engineering Interns
(65, 2, 15.00), (66, 2, 15.50),
-- ~10% of Members (RoleID=6) converted to hourly (3 members from Finance)
(27, 2, 20.00), (31, 2, 20.50), (35, 2, 21.00);

MERGE Org.HourlyEmployee T
USING (SELECT * FROM @HourlyEmployeeStaging) S ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.EmployeeTypeID <> S.EmployeeTypeID OR T.HourlyPay <> S.HourlyPay
) THEN
    UPDATE SET
        EmployeeTypeID = S.EmployeeTypeID,
        HourlyPay = S.HourlyPay
WHEN NOT MATCHED THEN
    INSERT([EmployeeID], [EmployeeTypeID], [HourlyPay])
    VALUES(S.EmployeeID, S.EmployeeTypeID, S.HourlyPay);
