DECLARE @PersonStaging TABLE
(
    AddressID INT NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50)
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @PersonStaging(AddressID, FirstName, LastName, Email, Phone)
VALUES
-- EXECUTIVES
-- CEO
(1, N'Robert', N'Johnson', N'robert.johnson@company.com', N'206-555-0101'),
-- HR Department Executive (reports to CEO)
(2, N'Sarah', N'Williams', N'sarah.williams@company.com', N'206-555-0102'),
-- Finance Department Executive (reports to CEO)
(3, N'Michael', N'Brown', N'michael.brown@company.com', N'206-555-0103'),
-- Sales Department Executive (reports to CEO)
(4, N'Jennifer', N'Davis', N'jennifer.davis@company.com', N'206-555-0104'),
-- Marketing Department Executive (reports to CEO)
(5, N'David', N'Miller', N'david.miller@company.com', N'206-555-0105'),
-- Engineering Department Executive (reports to CEO)
(6, N'Emily', N'Wilson', N'emily.wilson@company.com', N'206-555-0106'),

-- DIRECTORS
-- HR Director (reports to HR Executive)
(7, N'Christopher', N'Moore', N'christopher.moore@company.com', N'206-555-0107'),
-- Finance Director (reports to Finance Executive)
(8, N'Amanda', N'Taylor', N'amanda.taylor@company.com', N'206-555-0108'),
-- Sales Director (reports to Sales Executive)
(9, N'Matthew', N'Anderson', N'matthew.anderson@company.com', N'206-555-0109'),
-- Marketing Director (reports to Marketing Executive)
(10, N'Jessica', N'Thomas', N'jessica.thomas@company.com', N'206-555-0110'),
-- Engineering Director (reports to Engineering Executive)
(11, N'Daniel', N'Jackson', N'daniel.jackson@company.com', N'206-555-0111'),

-- MANAGERS
-- HR Manager (reports to HR Director)
(12, N'Ashley', N'White', N'ashley.white@company.com', N'206-555-0112'),
-- Finance Manager (reports to Finance Director)
(13, N'Andrew', N'Harris', N'andrew.harris@company.com', N'206-555-0113'),
-- Sales Manager (reports to Sales Director)
(14, N'Stephanie', N'Martin', N'stephanie.martin@company.com', N'206-555-0114'),
-- Marketing Manager (reports to Marketing Director)
(15, N'Joshua', N'Garcia', N'joshua.garcia@company.com', N'206-555-0115'),
-- Engineering Manager (reports to Engineering Director)
(16, N'Megan', N'Martinez', N'megan.martinez@company.com', N'206-555-0116'),

-- DEPARTMENTS
-- HR Department
(17, N'Ryan', N'Robinson', N'ryan.robinson@company.com', N'206-555-0117'),
(18, N'Nicole', N'Clark', N'nicole.clark@company.com', N'206-555-0118'),
(19, N'Brandon', N'Rodriguez', N'brandon.rodriguez@company.com', N'206-555-0119'),
(20, N'Samantha', N'Lewis', N'samantha.lewis@company.com', N'206-555-0120'),
(21, N'Kevin', N'Lee', N'kevin.lee@company.com', N'206-555-0121'),
(22, N'Lauren', N'Walker', N'lauren.walker@company.com', N'206-555-0122'),
(23, N'Stephen', N'Hall', N'stephen.hall@company.com', N'206-555-0123'),
(24, N'Rachel', N'Allen', N'rachel.allen@company.com', N'206-555-0124'),
(25, N'Timothy', N'Young', N'timothy.young@company.com', N'206-555-0125'),
(26, N'Brittany', N'King', N'brittany.king@company.com', N'206-555-0126'),
-- Finance Department
(27, N'Jonathan', N'Wright', N'jonathan.wright@company.com', N'206-555-0127'),
(28, N'Monica', N'Lopez', N'monica.lopez@company.com', N'206-555-0128'),
(29, N'Nathan', N'Hill', N'nathan.hill@company.com', N'206-555-0129'),
(30, N'Heather', N'Scott', N'heather.scott@company.com', N'206-555-0130'),
(31, N'Eric', N'Green', N'eric.green@company.com', N'206-555-0131'),
(32, N'Stephanie', N'Adams', N'stephanie.adams@company.com', N'206-555-0132'),
(33, N'Jacob', N'Baker', N'jacob.baker@company.com', N'206-555-0133'),
(34, N'Christina', N'Gonzalez', N'christina.gonzalez@company.com', N'206-555-0134'),
(35, N'Zachary', N'Nelson', N'zachary.nelson@company.com', N'206-555-0135'),
(36, N'Kayla', N'Carter', N'kayla.carter@company.com', N'206-555-0136'),
-- Sales Department
(37, N'Alexander', N'Mitchell', N'alexander.mitchell@company.com', N'206-555-0137'),
(38, N'Amber', N'Perez', N'amber.perez@company.com', N'206-555-0138'),
(39, N'Noah', N'Roberts', N'noah.roberts@company.com', N'206-555-0139'),
(40, N'Courtney', N'Turner', N'courtney.turner@company.com', N'206-555-0140'),
(41, N'William', N'Phillips', N'william.phillips@company.com', N'206-555-0141'),
(42, N'Steven', N'Campbell', N'steven.campbell@company.com', N'206-555-0142'),
(43, N'Benjamin', N'Parker', N'benjamin.parker@company.com', N'206-555-0143'),
(44, N'Brittany', N'Evans', N'brittany.evans@company.com', N'206-555-0144'),
(45, N'Samuel', N'Edwards', N'samuel.edwards@company.com', N'206-555-0145'),
(46, N'Rachel', N'Collins', N'rachel.collins@company.com', N'206-555-0146'),
-- Marketing Department
(47, N'Henry', N'Stewart', N'henry.stewart@company.com', N'206-555-0147'),
(48, N'Sandra', N'Sanchez', N'sandra.sanchez@company.com', N'206-555-0148'),
(49, N'Derek', N'Morris', N'derek.morris@company.com', N'206-555-0149'),
(50, N'Laura', N'Rogers', N'laura.rogers@company.com', N'206-555-0150'),
(51, N'Patrick', N'Cox', N'patrick.cox@company.com', N'206-555-0151'),
(52, N'Steven', N'Howard', N'steven.howard@company.com', N'206-555-0152'),
(53, N'Angela', N'Ward', N'angela.ward@company.com', N'206-555-0153'),
(54, N'Jason', N'Torres', N'jason.torres@company.com', N'206-555-0154'),
(55, N'Michelle', N'Peterson', N'michelle.peterson@company.com', N'206-555-0155'),
(56, N'Donald', N'Gray', N'donald.gray@company.com', N'206-555-0156'),
-- Engineering Department
(57, N'Susan', N'Ramirez', N'susan.ramirez@company.com', N'206-555-0157'),
(58, N'Paul', N'James', N'paul.james@company.com', N'206-555-0158'),
(59, N'Karen', N'Watson', N'karen.watson@company.com', N'206-555-0159'),
(60, N'Mark', N'Brooks', N'mark.brooks@company.com', N'206-555-0160'),
(61, N'Lisa', N'Kelly', N'lisakelly@company.com', N'206-555-0161'),
(62, N'James', N'Davis', N'james.davis@company.com', N'206-555-0162'),
(63, N'Sarah', N'Miller', N'sarah.miller@company.com', N'206-555-0163'),
(64, N'Thomas', N'Wilson', N'thomas.wilson@company.com', N'206-555-0164'),
(65, N'Nancy', N'Moore', N'nancy.moore@company.com', N'206-555-0165'),
(66, N'David', N'Taylor', N'david.taylor@company.com', N'206-555-0166');


MERGE Org.Person T
USING (SELECT * FROM @PersonStaging) S ON T.Email = S.Email
WHEN MATCHED AND (
    T.AddressID <> S.AddressID
    OR T.FirstName <> S.FirstName
    OR T.LastName <> S.LastName
    OR T.Phone <> S.Phone
) THEN
    UPDATE SET FirstName = S.FirstName, LastName = S.LastName, Phone = S.Phone
WHEN NOT MATCHED THEN
    INSERT(AddressID, FirstName, LastName, Email, Phone)
    VALUES(S.AddressID, S.FirstName, S.LastName, S.Email, S.Phone);
