DECLARE @SalaryEmployeeStaging TABLE
(
    EmployeeID INT NOT NULL PRIMARY KEY,
    SalaryID INT NOT NULL,
    PaidTimeOffHours INT NOT NULL,
    SickHours INT NOT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
-- SalaryEmployee records for all salary employees (EmployeeTypeID=1)
-- Only employees with salary employment type receive salary data
-- Higher positions receive higher salaries as per the salary structure

INSERT @SalaryEmployeeStaging(EmployeeID, SalaryID, PaidTimeOffHours, SickHours) VALUES
(1, 1, 141, 77),
(2, 2, 151, 90),
(3, 3, 107, 82),
(4, 4, 179, 86),
(5, 5, 137, 70),
(6, 6, 131, 81),
(8, 7, 120, 77),
(9, 8, 91, 82),
(11, 9, 154, 89),
(12, 10, 128, 45),
(13, 11, 173, 58),
(14, 12, 96, 51),
(15, 13, 197, 44),
(16, 14, 90, 60),
(17, 15, 139, 72),
(18, 16, 164, 97),
(19, 17, 91, 41),
(20, 18, 132, 95),
(21, 19, 89, 100),
(22, 20, 194, 45),
(23, 21, 94, 93),
(24, 22, 158, 92),
(25, 23, 153, 40),
(29, 24, 166, 46),
(30, 25, 99, 67),
(31, 26, 106, 92),
(32, 27, 160, 92),
(33, 28, 144, 88),
(34, 29, 88, 80),
(35, 30, 161, 71),
(36, 31, 136, 44),
(37, 32, 117, 94),
(38, 33, 135, 77),
(39, 34, 165, 77),
(40, 35, 142, 91),
(41, 36, 141, 100),
(42, 37, 164, 70),
(43, 38, 198, 78),
(44, 39, 122, 47),
(45, 40, 144, 50),
(46, 41, 131, 92),
(47, 42, 197, 77),
(49, 43, 142, 92),
(50, 44, 87, 53),
(51, 45, 115, 82),
(53, 46, 166, 82),
(54, 47, 98, 80),
(55, 48, 165, 100),
(56, 49, 176, 91),
(58, 50, 97, 84),
(59, 51, 95, 68),
(60, 52, 185, 51),
(61, 53, 180, 45),
(62, 54, 167, 63),
(63, 55, 155, 88),
(64, 56, 197, 63),
(65, 57, 158, 78),
(66, 58, 148, 94),
(67, 59, 84, 48),
(68, 60, 105, 90),
(69, 61, 129, 98),
(70, 62, 199, 85),
(71, 63, 160, 49),
(72, 64, 196, 45),
(74, 65, 113, 58),
(75, 66, 130, 96),
(76, 67, 97, 46),
(77, 68, 165, 61),
(78, 69, 188, 48),
(79, 70, 152, 97),
(80, 71, 135, 91),
(81, 72, 98, 62),
(82, 73, 151, 65),
(83, 74, 171, 68),
(84, 75, 96, 95),
(85, 76, 162, 88),
(86, 77, 163, 96),
(87, 78, 123, 84),
(88, 79, 196, 88),
(89, 80, 138, 58),
(90, 81, 180, 90),
(91, 82, 176, 91);

MERGE Org.SalaryEmployee T
USING (SELECT * FROM @SalaryEmployeeStaging) S ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.SalaryID <> S.SalaryID OR
    T.PaidTimeOffHours <> S.PaidTimeOffHours OR
    T.SickHours <> S.SickHours
) THEN
    UPDATE SET
        SalaryID = S.SalaryID,
        PaidTimeOffHours = S.PaidTimeOffHours,
        SickHours = S.SickHours
WHEN NOT MATCHED THEN
    INSERT(EmployeeID, SalaryID, PaidTimeOffHours, SickHours)
    VALUES(S.EmployeeID, S.SalaryID, S.PaidTimeOffHours, S.SickHours);
