DECLARE @HourlyEmployeeStaging TABLE
(
    [EmployeeID] INT NOT NULL,
    [EmployeeTypeID] INT NOT NULL,
    [HourlyPay] DECIMAL(18, 2) NOT NULL,
    [MaxHoursPerWeek] INT NULL
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @HourlyEmployeeStaging([EmployeeID], [EmployeeTypeID], [HourlyPay], [MaxHoursPerWeek])
VALUES
-- All Interns (RoleID=1) converted to hourly
-- HR Interns
(17, 2, 15.00, 35), (19, 2, 15.50, 32), (21, 2, 16.00, 38), (23, 2, 16.50, 30), (25, 2, 17.00, 40),
-- Finance Interns
(28, 2, 15.00, 28), (30, 2, 15.50, 33), (32, 2, 16.00, 36), (34, 2, 16.50, 29), (36, 2, 17.00, 42),
-- Sales Interns
(37, 2, 15.00, 37), (39, 2, 15.50, 31), (41, 2, 16.00, 39), (43, 2, 16.50, 27), (45, 2, 17.00, 41),
-- Marketing Interns
(48, 2, 15.00, 34), (50, 2, 15.50, 30), (52, 2, 16.00, 38), (54, 2, 16.50, 26), (56, 2, 17.00, 43),
-- Engineering Interns
(65, 2, 15.00, NULL), (66, 2, 15.50, NULL),
-- ~10% of Members (RoleID=6) converted to hourly (3 members from Finance)
(27, 2, 20.00, NULL), (31, 2, 20.50, NULL), (35, 2, 21.00, NULL);

MERGE Org.HourlyEmployee T
USING (SELECT * FROM @HourlyEmployeeStaging) S ON T.EmployeeID = S.EmployeeID
WHEN MATCHED AND (
    T.EmployeeTypeID <> S.EmployeeTypeID
    OR T.HourlyPay <> S.HourlyPay
    OR T.MaxHoursPerWeek <> S.MaxHoursPerWeek
) THEN
    UPDATE SET
        EmployeeTypeID = S.EmployeeTypeID,
        HourlyPay = S.HourlyPay,
        MaxHoursPerWeek = S.MaxHoursPerWeek
WHEN NOT MATCHED THEN
    INSERT([EmployeeID], [EmployeeTypeID], [HourlyPay], [MaxHoursPerWeek])
    VALUES(S.EmployeeID, S.EmployeeTypeID, S.HourlyPay, S.MaxHoursPerWeek);
