DECLARE @EmployeeStaging TABLE
(
    ManagerID INT,
    PersonID INT NOT NULL,
    EmployeeTypeID INT NOT NULL,
    HireDate DATETIME2 NOT NULL,
    TerminationDate DATETIME2
);

-- Data generated by RooCode - Local qwen/qwen3.5-9b
INSERT @EmployeeStaging(ManagerID, PersonID, EmployeeTypeID, HireDate, TerminationDate)
VALUES
-- CEO (reports to NULL)
(NULL, 1, 1, '2020-01-01', NULL),
-- HR Department Executive (reports to CEO)
(1, 2, 1, '2020-02-01', NULL),
-- Finance Department Executive (reports to CEO)
(1, 3, 1, '2020-02-01', NULL),
-- Sales Department Executive (reports to CEO)
(1, 4, 1, '2020-02-01', NULL),
-- Marketing Department Executive (reports to CEO)
(1, 5, 1, '2020-02-01', NULL),
-- Engineering Department Executive (reports to CEO)
(1, 6, 1, '2020-02-01', NULL),
-- HR Director (reports to HR Executive)
(2, 7, 1, '2020-03-01', NULL),
-- Finance Director (reports to Finance Executive)
(3, 8, 1, '2020-03-01', NULL),
-- Sales Director (reports to Sales Executive)
(4, 9, 1, '2020-03-01', NULL),
-- Marketing Director (reports to Marketing Executive)
(5, 10, 1, '2020-03-01', NULL),
-- Engineering Director (reports to Engineering Executive)
(6, 11, 1, '2020-03-01', NULL),
-- HR Manager (reports to HR Director)
(7, 12, 1, '2020-04-01', NULL),
-- Finance Manager (reports to Finance Director)
(8, 13, 1, '2020-04-01', NULL),
-- Sales Manager (reports to Sales Director)
(9, 14, 1, '2020-04-01', NULL),
-- Marketing Manager (reports to Marketing Director)
(10, 15, 1, '2020-04-01', NULL),
-- Engineering Manager (reports to Engineering Director)
(11, 16, 1, '2020-04-01', NULL),
-- HR Staff (reports to HR Manager)
(12, 17, 2, '2020-05-01', NULL),
(12, 18, 1, '2020-05-01', NULL),
(12, 19, 2, '2020-05-01', NULL),
(12, 20, 1, '2020-05-01', NULL),
(12, 21, 2, '2020-05-01', NULL),
(12, 22, 1, '2020-05-01', NULL),
(12, 23, 2, '2020-05-01', NULL),
(12, 24, 1, '2020-05-01', NULL),
(12, 25, 2, '2020-05-01', NULL),
(12, 26, 1, '2020-05-01', NULL),
-- Finance Staff (reports to Finance Manager)
(13, 27, 2, '2020-05-01', NULL),
(13, 28, 1, '2020-05-01', NULL),
(13, 29, 2, '2020-05-01', NULL),
(13, 30, 1, '2020-05-01', NULL),
(13, 31, 2, '2020-05-01', NULL),
(13, 32, 1, '2020-05-01', NULL),
(13, 33, 2, '2020-05-01', NULL),
(13, 34, 1, '2020-05-01', NULL),
(13, 35, 2, '2020-05-01', NULL),
(13, 36, 1, '2020-05-01', NULL),
-- Sales Staff (reports to Sales Manager)
(14, 37, 2, '2020-05-01', NULL),
(14, 38, 1, '2020-05-01', NULL),
(14, 39, 2, '2020-05-01', NULL),
(14, 40, 1, '2020-05-01', NULL),
(14, 41, 2, '2020-05-01', NULL),
(14, 42, 1, '2020-05-01', NULL),
(14, 43, 2, '2020-05-01', NULL),
(14, 44, 1, '2020-05-01', NULL),
(14, 45, 2, '2020-05-01', NULL),
(14, 46, 1, '2020-05-01', NULL),
-- Marketing Staff (reports to Marketing Manager)
(15, 47, 2, '2020-05-01', NULL),
(15, 48, 1, '2020-05-01', NULL),
(15, 49, 2, '2020-05-01', NULL),
(15, 50, 1, '2020-05-01', NULL),
(15, 51, 2, '2020-05-01', NULL),
(15, 52, 1, '2020-05-01', NULL),
(15, 53, 2, '2020-05-01', NULL),
(15, 54, 1, '2020-05-01', NULL),
(15, 55, 2, '2020-05-01', NULL),
(15, 56, 2, '2020-05-01', NULL),
-- Engineering Staff (all report to Engineering Manager)
(16, 57, 1, '2020-05-01', NULL),
(16, 58, 1, '2020-05-01', NULL),
(16, 59, 1, '2020-05-01', NULL),
(16, 60, 1, '2020-05-01', NULL),
(16, 61, 1, '2020-05-01', NULL),
(16, 62, 1, '2020-05-01', NULL),
(16, 63, 2, '2020-05-01', NULL),
(16, 64, 2, '2020-05-01', NULL),
(16, 65, 2, '2020-05-01', NULL),
(16, 66, 2, '2020-05-01', NULL);

MERGE Org.Employee T
USING (SELECT * FROM @EmployeeStaging) S ON T.PersonID = S.PersonID
WHEN MATCHED AND (
    T.ManagerID <> S.ManagerID OR
    T.EmployeeTypeID <> S.EmployeeTypeID OR
    T.HireDate <> S.HireDate OR
    T.TerminationDate <> S.TerminationDate
) THEN
    UPDATE SET 
        ManagerID = S.ManagerID,
        EmployeeTypeID = S.EmployeeTypeID,
        HireDate = S.HireDate,
        TerminationDate = S.TerminationDate
WHEN NOT MATCHED THEN
    INSERT(ManagerID, PersonID, EmployeeTypeID, HireDate, TerminationDate)
    VALUES(S.ManagerID, S.PersonID, S.EmployeeTypeID, S.HireDate, S.TerminationDate);
